### PR TITLE
Memory sparklines

### PR DESCRIPTION
**Pull request by jtpio**
Switch between bar and sparklines views on click.

memory-view-lines

### CODE REVIEW

**Comment by mathematicalmichael** [comment]
this is an awesome feature! just re-built a container where I install your package and saw the update. Thanks for your work!

**Comment by jtpio** [comment]
Thanks for the feedback!

The Binder version should now also be up-to-date.

**Comment by mathematicalmichael** [comment]
awesome! yeah, happy to help. love what you've done here and will be rolling it out to production (students on a department jupyterhub server) soon! 
for some reason I'm still not seeing the menu to toggle nor how to set the text area yet. Maybe I should do another build?

**Comment by jtpio** [comment]
To toggle the topbar space the `jupyterlab-topbar-extension` should also be updated:

```
$ jupyter labextension list

...
jupyterlab-topbar-extension v0.2.0  enabled  OK
...
```

And for the text area it's another extension to install:

`jupyter labextension install jupytelab-topbar-text`

**Pull request merged**
